### ISSUE TITLE
`Property` node type

### ISSUE THREAD

**Issue by fvictorio** [suchipi/grep-ast#4]
Not sure if this is an issue with `grep-ast`, `esquery` or my own understanding, but given this file:

```js
const a = {
  foo: false
}
```

`grep-ast Property` doesn't return anything, even if that node shows up in AST Explorer.

**Comment by fvictorio** [comment]
FWIW `Property` does return results in https://estools.github.io/esquery/

**Comment by suchipi** [comment]
This is because the default parser in grep-ast is `@babel/parser` and the default options don't have the `estree` option set, so this node is instead called `ObjectProperty`.

If you need it to be called `Property`, you can either pass a custom `--parserOptions` that has `estree` set to true, or use the `--parser` flag to specify a different parser; for example, `esprima`.

To explore how `@babel/parser` behaves without `estree` set, you can use [AST Explorer](https://astexplorer.net/). Choose JavaScript, babylon7, and then press the gear next to babylon7 to open its settings, and uncheck "estree".

**Comment by fvictorio** [comment]
Oops, thanks, I thought `esprima` was being used because that's what it says in the `esquery` repository, sorry about that!

> To explore how @babel/parser behaves without estree set, you can use AST Explorer. Choose JavaScript, babylon7, and then press the gear next to babylon7 to open its settings, and uncheck "estree".

I think it would be very useful to have that in the readme, btw.

**Comment by suchipi** [comment]
Thanks for the idea; I added that to the readme.
